### ISSUE TITLE
i got no clue what too call this 

### ISSUE THREAD

**Issue by ExiledTank** [smitty-diamond-hunt/idle-pixel-bug-tracking#12]
https://gyazo.com/89a3199feaeeb2776bf28b70edc3c7d3  on login getting combat area background till tab change

**Comment by smitty-diamond-hunt** [comment]
Are you able to reproduce this?  No one else has had this bug and I cannot reproduce it

**Comment by smitty-diamond-hunt** [comment]
Plus your using addons coded from Anwinity which could cause problems.

**Comment by happylord7** [comment]
Hi, i wanted to add something to this.
Loading screen takes long on my part, it loads the game with a background of the last field you fought in, whenever you swap to another tab and back to key items its gone
https://i.gyazo.com/16d2b63601f1bf74a3413f3fc176f0e0.gif

**Comment by smitty-diamond-hunt** [comment]
Appreciate the gif, testing it now

**Comment by smitty-diamond-hunt** [comment]
Fixed it, thx
