### ISSUE TITLE
Stardust logs - heat not working

### ISSUE THREAD

**Issue by anton-shestakov** [smitty-diamond-hunt/idle-pixel-bug-tracking#13]
According to tooltip, burning stardust logs should give 6 heat per log (I have cooking achievements completed)

But when I burn those logs I get enormous amount of stardust immediately, and then second after I get only 1 heat per log applied instantly (it's probably due to oven booster, but total amount is incorrect). See video below

https://user-images.githubusercontent.com/21039120/182042492-ec1d80b1-0fb7-4f12-8167-0a4e4edd63bb.mp4

**Comment by smitty-diamond-hunt** [comment]
Fixed
