### ISSUE TITLE
Axe showing up in socket scroll even if I don't have the axe

### ISSUE THREAD

**Issue by felixbilodeau** [smitty-diamond-hunt/idle-pixel-bug-tracking#14]
I don't have the axe, but I do have the socket scroll. When I go into the socket scroll it says that I can upgrade the axe even though I don't have it. Other tools I don't have say "You don't have this tool yet", but the axe says "Each upgrade increases your logs by +5 for every tree" with an upgrade button even though I don't have it

**Comment by smitty-diamond-hunt** [comment]
Fixed
