### ISSUE TITLE
stardust bar issue again

### ISSUE THREAD

**Issue by ExiledTank** [smitty-diamond-hunt/idle-pixel-bug-tracking#15]
stardust bar issue still showing up on iron bars in large amounts
3k+

**Comment by ExiledTank** [comment]
more stuff 9k should be teh base cost of 40 bars the 9720 is useing the 27xp per bar from donor perk yet some reason it costs over 10k
https://gyazo.com/333905a7a5dfbffc49fd77a89793b202

**Comment by ExiledTank** [comment]
part 2 of testing it seems bars dont give hte proper xp the xp isnt proper per bar
getting 1080 xp for 40 bars useing 27
n if it was the 27.5 xp would be 1100
but in the screen getting 1188

**Comment by ExiledTank** [comment]
round 3 donor perk is apply 2 times on the xp for bars  n is effecting cost
https://gyazo.com/1f9c73773b9eded690cd26e37254511d?token=6ca7d5024a229210407024268408727b

**Comment by ExiledTank** [comment]
round 4 mining xp does the same thing

**Comment by ExiledTank** [comment]
extra update all bars are effected by doublefrom iron-gold are getting dobule donor perk for xp
sd price for these 3 are wrong also
bronze bar isnt effect my guess the xp per bar  isnt enuff for donor too give  more then base xp

**Comment by smitty-diamond-hunt** [comment]
fixed
