### ISSUE TITLE
Tooltip error in brewing kit

### ISSUE THREAD

**Issue by felixbilodeau** [smitty-diamond-hunt/idle-pixel-bug-tracking#17]
In the socket scroll, when upgrading the brewing kit, it says that each upgrade increases potion timers by 25%. However, after upgrading it once, in the brewing tab, when hovering on the brewing kit, it says that there is now a +5% potion timers. Judging by the actual potion timers, I calculate that the upgrade is actually 25%, so the tooltip in the brewing tab seems to be incorrect.

**Comment by smitty-diamond-hunt** [comment]
Thanks!  Fixed ;)
