### ISSUE TITLE
login

### ISSUE THREAD

**Issue by ExiledTank** [smitty-diamond-hunt/idle-pixel-bug-tracking#21]
some times logging u just get a blank screen 
https://gyazo.com/5ee35cec847f1899f0396c8ae5eccff7
turned scripted off too see if was cause n its still blank

**Comment by happylord7** [comment]
I sometimes have the same issue on both my phone and my computer, simply refreshing the page helps, not really an issie but kind of annoying

**Comment by smitty-diamond-hunt** [comment]
Yeah, it seems to happen like 5  - 10% of the time with me too.

Most likely will have to take a look at the login flow in code to see what's going on.  I don't get any exceptions on server/client

**Comment by smitty-diamond-hunt** [comment]
Still trying to reproduce this, can't seem to do it...
