### ISSUE TITLE
Tree Speed Potion is called Farming Speed Potion when hovering the name

### ISSUE THREAD

**Issue by gowerr** [smitty-diamond-hunt/idle-pixel-bug-tracking#22]
I believe I've discovered a bug related to the Tree Speed Potion.

When hovering over the name of the Tree Speed Potion, it's called Farming Speed Potion. Isn't it supposed to be Tree Speed Potion instead? 

Also it has the same description of the Farming Speed Potion.

 Here's a screenshot. 

https://i.imgur.com/iCU9vIl.png

**Comment by smitty-diamond-hunt** [comment]
Fixed and closed, thanks.
