### ISSUE TITLE
Cannot click on ores or bars after August 10th update

### ISSUE THREAD

**Issue by gowerr** [smitty-diamond-hunt/idle-pixel-bug-tracking#23]
After the recent update, I can no longer left click on my bars or ores. This means I can't sell or use them for XP.

Here's a GIF I recorded.

https://i.imgur.com/NpoikZP.gif

**Comment by happylord7** [comment]
Same problem was about to report

**Comment by smitty-diamond-hunt** [comment]
Fixed, along with max button (max btn was only bugged for stone)
