### ISSUE TITLE
Shiny glass orb

### ISSUE THREAD

**Issue by happylord7** [smitty-diamond-hunt/idle-pixel-bug-tracking#25]
Was it ment to be able to make more shiny glass orbs then you can enchant?
https://gyazo.com/4f2f98aa59a85c1ddd21144862b3df8b

**Comment by smitty-diamond-hunt** [comment]
There was a previous bug that when enchanting a shiny orb did not consume the orb itself, perhaps you had the bug and that's why you can craft more?  Leaving it open to wait for your confirmation

**Comment by happylord7** [comment]
Yes i made multiple orbs te first time with one glass orb, you can close this
