### ISSUE TITLE
Question - how to craft Charcoal Foundry

### ISSUE THREAD

**Issue by anton-shestakov** [smitty-diamond-hunt/idle-pixel-bug-tracking#26]
As title says, it requires a prometheum but it seems like it's not possible to craft prometheum from ore without charcoal. So looks like chicken and egg problem. Could it be that 1 prometheum can be dropped from Ice monsters (I haven't killed any yet because they are too strong xD)?

**Comment by happylord7** [comment]
Prometium bar is not dropped by ice monster, i think (not sure about this) the only way is to get it via the pirate chest, definitely an overlook, it should be easier to obtain the first prometium bar imo, either from a shop or from a drop or from a quest

**Comment by smitty-diamond-hunt** [comment]
You can also get prom from using the bomb obtained in volcano.  I think it's a 1/2 chance of getting an ore, and 1/4 for a bar.

Def. need to add another source, ill keep this open until then
