### ISSUE TITLE
Fishing achievement - not applied

### ISSUE THREAD

**Issue by anton-shestakov** [smitty-diamond-hunt/idle-pixel-bug-tracking#3]
Hi,

After adding fishing achievements, the one that says 

`Upgrade your fishing net with a sapphire.`

has not been applied retroactively. I have fishing net upgraded with a sapphire and can't do that twice obviously.

![image](https://user-images.githubusercontent.com/21039120/181292049-b5253841-d61a-4789-91a2-6ee0832eef67.png)

So either it should have been calculated for existing players or it should say about any upgrade (although next level is much harder to get than just sapphire).

Partially same can be said about `Catch a very rare fish.` I have some catch during the play (Piranha, Eel, Rainbow) but they were catch before the achievement added. But I guess it's fine to be applied for future catch only, as it's pretty much the same catch as before.

**Comment by smitty-diamond-hunt** [comment]
Fixed, both achievement will be automatically completed during next game update.

**Comment by smitty-diamond-hunt** [comment]
Seems like one player is saying it didn't work even after the patch, will investigate
