### ISSUE TITLE
post all spelling mistakes here

### ISSUE THREAD

**Issue by ExiledTank** [smitty-diamond-hunt/idle-pixel-bug-tracking#38]
https://gyazo.com/4f9e9d6902b97a45440bbe0d1e9f9335 reflect **(FIXED)**
https://gyazo.com/a9c6118ada6cfe44599ad6473e7c8d60 excluding **(FIXED)**

**Comment by ExiledTank** [comment]
https://gyazo.com/a9c6118ada6cfe44599ad6473e7c8d60 excluding

**Comment by smitty-diamond-hunt** [comment]
let's post these in #spelling-mistakes on disc
