### ISSUE TITLE
Tooltip error for green leaf seeds

### ISSUE THREAD

**Issue by felixbilodeau** [smitty-diamond-hunt/idle-pixel-bug-tracking#5]
When hovering over green leaf seeds in the farming section, the tooltip says the required level is 15. However, when trying to plant them when you are not the right level, the error box that shows up says you have to be level 10. I'm not sure which one is correct, but one of them has to be wrong :)

**Comment by smitty-diamond-hunt** [comment]
The actual level required is 10, so yeah a tooltip error.

I fixed this now, itll be pushed on next release!

Thanks :)

p.s. the dieing farming level is 25, not 30.  Also fixed
