### ISSUE TITLE
general typos

### ISSUE THREAD

**Issue by NickBastien** [smitty-diamond-hunt/idle-pixel-bug-tracking#55]
![image](https://user-images.githubusercontent.com/5890606/190169016-a0f83ac1-5039-46c5-b50e-ff247982d1d1.png)

**Comment by NickBastien** [comment]
When you die, it says: you have died in a combat fight. I would change it to: "you died in combat" or "you died in a fight".

**Comment by smitty-diamond-hunt** [comment]
fixed ty
