### ISSUE TITLE
Backend doesn't check requirements for fighting at mansion

### ISSUE THREAD

**Issue by Anwinity** [smitty-diamond-hunt/idle-pixel-bug-tracking#64]
Normal UI doesn't let you go to mansion without all 4 crystals, but with quick-fight if you submit the request to start a fight there the backend does not check requirements.

Quick-Fight can be changed to prevent this from its UI, but back end really should prevent this as well (otherwise a player can easily bypass it if they know what they are doing).

**Comment by smitty-diamond-hunt** [comment]
Turns out it's the same for NF and Volcano, fixed all 3 thanks
